// <auto-generated />
using System;
using Booking.Infrastruture.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Booking.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260323212548_FixModel")]
    partial class FixModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BarberEntityServiceEntity", b =>
                {
                    b.Property<Guid>("BarbersId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SpecializationsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BarbersId", "SpecializationsId");

                    b.HasIndex("SpecializationsId");

                    b.ToTable("BarberServices", (string)null);
                });

            modelBuilder.Entity("Booking.Infrastruture.Persistence.AppointmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BarberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comments")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ScheduledTimeEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ScheduledTimeStart")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BarberId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            BarberId = new Guid("a47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            Comments = "First appointment",
                            CustomerId = new Guid("c47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            ScheduledTimeEnd = new DateTime(2026, 3, 23, 11, 20, 0, 0, DateTimeKind.Unspecified),
                            ScheduledTimeStart = new DateTime(2026, 3, 23, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            ServiceId = new Guid("b47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            Status = 1
                        });
                });

            modelBuilder.Entity("Booking.Infrastruture.Persistence.BarberEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Barbers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            Name = "Łukasz"
                        });
                });

            modelBuilder.Entity("Booking.Infrastruture.Persistence.CustomerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            Email = "none@example.com",
                            Name = "John Doe"
                        });
                });

            modelBuilder.Entity("Booking.Infrastruture.Persistence.ServiceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PriceAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            DurationMinutes = 20,
                            Name = "Beard Trim",
                            PriceAmount = 110m
                        });
                });

            modelBuilder.Entity("BarberEntityServiceEntity", b =>
                {
                    b.HasOne("Booking.Infrastruture.Persistence.BarberEntity", null)
                        .WithMany()
                        .HasForeignKey("BarbersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booking.Infrastruture.Persistence.ServiceEntity", null)
                        .WithMany()
                        .HasForeignKey("SpecializationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Booking.Infrastruture.Persistence.AppointmentEntity", b =>
                {
                    b.HasOne("Booking.Infrastruture.Persistence.BarberEntity", "Barber")
                        .WithMany()
                        .HasForeignKey("BarberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booking.Infrastruture.Persistence.CustomerEntity", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Booking.Infrastruture.Persistence.ServiceEntity", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barber");

                    b.Navigation("Customer");

                    b.Navigation("Service");
                });
#pragma warning restore 612, 618
        }
    }
}
